throw error in code
error name [object object]
result => Ø¯Ø± Ù‚Ø³Ù…Øª Ø³Ø±ÙˆØ± Ù…Ø´Ú©Ù„Ø¯ Ø¯Ø§Ø´ØªÛŒÙ…

#before
this.#app.use((req, res, next)ðŸ”´error

#after
this.#app.use((error, req, res, next)ðŸŸ¢fixed